### ISSUE TITLE
can't set data_directory in config

### ISSUE THREAD

**Issue by luck02** [hw-cookbooks/postgresql#143]
When my postgresql config is:
```
name "postgres_db"
description "The base role for systems that have postgres"

run_list "recipe[postgresql::server]",
		 "recipe[postgresql::ruby]"

default_attributes postgresql: {
		config:		   {
			listen_addresses: '*',
            ssl_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key",
			ssl_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem",
			data_directory: '/opt/paybyphone/postgres'
		},
		password:	   { postgres: 'postgres' },
		version:	   "9.3",
		pg_hba:		   [
			{type: 'local', db: 'all', user: 'postgres', addr: nil, 	          :method => 'ident'},
			{type: 'local', db: 'all', user: 'all',		 addr: nil, 	          :method => 'ident'},
			{type: 'host',  db: 'all', user: 'all',		 addr: '127.0.0.1/32',    :method => 'md5'  },
			{type: 'host',  db: 'all', user: 'all',		 addr: '10.0.2.0/24',     :method => 'md5'  },
			{type: 'host',  db: 'all', user: 'all',		 addr: '10.0.3.0/24',     :method => 'md5'  },
			{type: 'host',  db: 'all', user: 'all',		 addr: '192.168.42.0/24', :method => 'md5'  },
		],
		enable_pgdg_apt: 'true',
	}
```

Then the 'data_directory' config piece breaks the install.

I get the following in my output:
```
Running handlers:[0m

[2014-05-15T07:41:36-07:00] ERROR: Running exception handlers

Running handlers complete

[0m

[2014-05-15T07:41:36-07:00] ERROR: Exception handlers complete

[2014-05-15T07:41:36-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out

Chef Client failed. 28 resources updated in 65.266902432 seconds[0m

[2014-05-15T07:41:36-07:00] ERROR: service[postgresql] (postgresql::server_debian line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'

---- Begin output of /etc/init.d/postgresql restart ----

STDOUT: * Restarting PostgreSQL 9.3 database server

 * Error: pid file is invalid, please manually kill the stale server process.

   ...fail!
```

I'm a little confused as to why this config works from the standpoint of being available in the config but then breaks on restart.

full output here: http://tny.cz/843cbe61

Data Directory is available as a config in attributes.rb
```
  default['postgresql']['config']['data_directory'] = "/var/lib/postgresql/#{node['postgresql']['version']}/main"
```

Am I missing something fundamental?

**Comment by rwilcox** [comment]
I ran across this same issue, and tried the solution above.

However, I found this didn't work well: I ended up copying a corrupted postgres data store / postgres complained it wasn't shut down properly. Which makes sense, after all: this copy *does* just yank the files out from under postgres in a non-atomic way.

SOOOOO

My solution was to stop the postgres service right after installation, do the server config, run initdb if we have to, then start the server back up.

It doesn't copy the data from the previous location, which is fine by me. I suppose I could have stopped the server, run the copy `ruby_block` above, then restarted the server... but, eh? I'm a newbie postgres admin, but maybe there's something to be said about starting fresh (like if you set the character set in the config file or something??????). Or maybe rerunning `initdb` is silly... :question: :grey_question: 

Anyway, my changes to server_debian are below. I could probably submit a PR for this, or at least this may help future searchers.

    node['postgresql']['server']['packages'].each do |pg_pack|
      package pg_pack
    end

    # stop the service, because the pg daemon saves the pid file in the data folder...
    # and we may change the data file...
    # RPW 03-03-2015
    # ARRGHH. See: https://github.com/hw-cookbooks/postgresql/pull/174

    service "postgresql" do
      service_name node['postgresql']['server']['service_name']
      action :stop
    end

    include_recipe "postgresql::server_conf"


    # we may need to rerun initdb especially if we're startig from 0. RPW 03-04-2015
    execute "/usr/lib/postgresql/#{node['postgresql']['version']}/bin/initdb -D #{node['postgresql']['config']['data_directory']}" do
      not_if { ::FileTest.exist?(File.join(node['postgresql']['config']['data_directory'], "PG_VERSION")) }
      user "postgres"
    end

    service "postgresql" do
      service_name node['postgresql']['server']['service_name']
      supports :restart => true, :status => true, :reload => true
      action [:enable, :start]
    end

**Comment by slyness** [comment]
An old one... soon to be corrected. #314

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0

**Comment by gsaslis** [comment]
@slyness just tried this on a ubuntu 14.04 to see if 4.0.0 fixes the issue with the directory, however this issue still persists... : / 

p.s. Happy New Year!! :tada:
