### ISSUE TITLE
9.4 on Ubuntu 14.04

### ISSUE THREAD

**Issue by phillipsnick** [hw-cookbooks/postgresql#217]
Having a play with PostgreSQL and was hoping to install version 9.4 as this is the latest release.

Is it possible to install this version using this cookbook? I'd have assumed adding the following line to my attributes would have worked:

```ruby
default['postgresql']['version']  = '9.4'
default['postgresql']['password']['postgres'] = 'postgres'
```

But 9.3 is still installed, tried running the install command manually via terminal and it detects the package.

```bash
$ sudo apt-get install postgresql-9.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libpq-dev libpq5 postgresql-client-9.4
Suggested packages:
  postgresql-doc-9.4 oidentd ident-server locales-all
The following NEW packages will be installed:
  postgresql-9.4 postgresql-client-9.4
The following packages will be upgraded:
  libpq-dev libpq5
2 upgraded, 2 newly installed, 0 to remove and 74 not upgraded.
Need to get 4,912 kB of archives.
After this operation, 22.8 MB of additional disk space will be used.
```

Also looking in the apt sources 

```bash
$ cat /etc/apt/sources.list.d/apt.postgresql.org.list
deb     http://apt.postgresql.org/pub/repos/apt trusty-pgdg main 9.4
```

As I'm pretty new to this Chef automation I'm probably doing something completely wrong and it's probably blatantly obvious to someone who knows what they are doing :)

**Comment by phillipsnick** [comment]
So after a few hours of playing it turns out I can install 9.4 using this cookbook by using the following attributes.

```ruby
default['postgresql']['version']  =                     '9.4'

default['postgresql']['dir'] =                          "/etc/postgresql/#{default['postgresql']['version']}/main"
default['postgresql']['client']['packages'] =           ["postgresql-client-#{default['postgresql']['version']}", "libpq-dev"]
default['postgresql']['server']['packages'] =           ["postgresql-#{default['postgresql']['version']}"]
default['postgresql']['contrib']['packages'] =          ["postgresql-contrib-#{default['postgresql']['version']}"]

default['postgresql']['config']['data_directory'] =     "/var/lib/postgresql/#{default['postgresql']['version']}/main"
default['postgresql']['config']['hba_file'] =           "/etc/postgresql/#{default['postgresql']['version']}/main/pg_hba.conf"
default['postgresql']['config']['ident_file'] =         "/etc/postgresql/#{default['postgresql']['version']}/main/pg_ident.conf"
default['postgresql']['config']['external_pid_file'] =  "/var/run/postgresql/#{default['postgresql']['version']}-main.pid"
```

This is quite easily missed as I and a friend found out today, I think its fair to have to define the `packages` for `client`, `server`, and `contrib.

Is there no way of preventing the parts in `attributes/default.rb` that set `default['postgresql']['version']` from skipping if it has already been set. Assuming that Chef may load these files in a specific order which would prevent this!

**Comment by bkw** [comment]
+1 this is not really a satisfying workaround.

**Comment by stefanozanella** [comment]
I also ran into the same problem, and had to overwrite all the default attributes that by default were reading from `default['postgresql']['version']`. 

The issue is related to the way Chef evaluates attributes. Specifically, the attributes for a dependent cookbook are evaluated _before_ the attributes of the cookbook that uses them. In this case, by the time Chef evaluates the new value for `default['postgresql']['version']`, all other attributes deriving from that have already been evaluated with the old value.
The mechanics of this behavior are well explained [here](https://christinemdraper.wordpress.com/2014/10/06/avoiding-the-possible-pitfalls-of-derived-attributes/) along with some possible solutions.

From the cookbook point of view, a solution has already been proposed in #201, but no feedback has been sent yet. From the user perspective, I guess the only two solutions are the one already mentioned above and overwriting the version attribute in a role.
Personally, I'd very much like to see #201 moved forward, as it seems to give the user more flexibility in the way they use the cookbook itself.

**Comment by rmoriz** [comment]
Maybe using sprintf to merge version and directory structure later inside the recipes could be a solution to this?
https://coderanger.net/derived-attributes/

**Comment by stefanozanella** [comment]
Personally I prefer the solution posted in the mentioned PR as it keeps the code a bit shorter and easier to write. But it's just a matter of taste and yes, that solution would have practically the same effect.

**Comment by slyness** [comment]
Both solutions work in this case. I now have this under review and we should make a call on it and merge soon.

**Comment by stefanozanella** [comment]
Very cool, thanks!

**Comment by kplimack** [comment]
I opened a ticket, #234, pointing this out with my solution, but someone locked it taking it very personally, but I hope it helps

**Comment by IevgenKabanets** [comment]
Another thing I'm fighting, and it looks like related.

If I override version attribute in my wrapper - everything goes fine, until postgresql.conf template resource kicks in.

In attributes there is an 'if' statement, that uses version:
*default['postgresql']['config']['unix_socket_directory'] = '/var/run/postgresql' if node['postgresql']['version'].to_f < 9.3*
*default['postgresql']['config']['unix_socket_directories'] = '/var/run/postgresql' if node['postgresql']['version'].to_f >= 9.3*

In the end - both lines end up in conf file.
I tried putting copy of attributes file in my wrapper (overwriting all attribs and using 9.1 as version) - it won't work.

Anyone encountered such issue?

**Comment by mrjcleaver** [comment]
Maybe we can open the wiki on this git repo and - until such a time we sort out the issue in the repo - document how best to workaround it.

Wrapper cookbook? Role based overrides? Need fast info to something known to work.

**Comment by david-morton** [comment]
@IevgenKabanets ... apologies if this is now too long ago but just stumbled upon this thread and have recently solved your issue as we also faced it (PG 9.4 on Ubuntu 12.04 LTS). The below works in chef 11, technique may vary with version but intent will remain the same.

I use the below in the attributes file:
# The below is to ensure we get the correct socket directory config parameter name
# which was changed in PostgreSQL 9.3. The default version for Ubuntu 12.04 is
# 9.1 which uses the previous name 'unix_socket_directory'.
normal[:postgresql][:config][:unix_socket_directories] = '/var/run/postgresql'
node.default_attrs[:postgresql][:config].delete(:unix_socket_directory)

**Comment by slyness** [comment]
Looking forward to 4.0.0 where these issues will be corrected. #314

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0

**Comment by badmadrad** [comment]
I am still experiencing an issue in this ticket.

Despite setting postgres version to 9.4 its still evaluating the deprecated parameter:

`unrecognized configuration parameter "unix_socket_directory" in file "/etc/postgresql/9.4/main/postgresql.conf" line 22`

I looked at the code and their is a flag that should work in theory but its not.
     if node['postgresql']['version'].to_f < 9.3
      node.set['postgresql']['config']['unix_socket_directory'] = '/var/run/postgresql'
    else
      node.set['postgresql']['config']['unix_socket_directories'] = '/var/run/postgresql'

Haven't dug and deeper but I'll try the @david-morton workaround see if that helps.
