### ISSUE TITLE
Parent directory /etc/postgresql/9.4/main does not exist - Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rasheedamir** [hw-cookbooks/postgresql#261]
I have seen lots of people facing the same issue and I am facing it as well on Ubuntu 14.04 LTS!

```
template[/etc/postgresql/9.4/main/postgresql.conf] action create
    * Parent directory /etc/postgresql/9.4/main does not exist.
    ================================================================================
    Error executing action `create` on resource 'template[/etc/postgresql/9.4/main/postgresql.conf]'
    ================================================================================
    
    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    Parent directory /etc/postgresql/9.4/main does not exist.
```

I have tried all versions including 9.1, 9.2, 9.3 and 9.4 but luck.
Any idea how to fix it? Or get around it?

**Comment by chrisduong** [comment]
+1

**Comment by chrisduong** [comment]
Hi guys,

If we move this code **execute 'Set locale and Create cluster'** before the line - **include_recipe 'postgresql::server_conf'** in the 'postgresql::server_debian', it would create the folder and it won't fail.

It is a simple fix.

**Comment by slyness** [comment]
There will be corrections for this issue released soon. #314

**Comment by slyness** [comment]
Resolved as of release 4.0.0 - https://github.com/hw-cookbooks/postgresql/releases/tag/v4.0.0

**Comment by fiedl** [comment]
This, apparently, is still an issue on `postgresql 4.0.0`. Strangely, everything worked fine on vagrant. But, trying it out with a real ubuntu 14.04 server, the directory `/etc/postgresql` is actually empty.

I'm not sure why the locales on the system should have any impact on that. But can anyone see if there is anything wrong with my locales?

```bash
➜  locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

➜  env
LANG=en_US.UTF-8
LC_CTYPE=en_US
...
```

What is the proper way to fix this?
